version = 0.1
[default.deploy.parameters]
stack_name = "dev-sls-nextjs-app"
resolve_s3 = true
s3_prefix = "sls-nextjs-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
